version: "3.9"
services:
  db:
    image: postgres:16
    container_name: doctalk-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: doctalk
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d doctalk"]
      interval: 5s
      timeout: 3s
      retries: 15

  redis:
    image: redis:7
    container_name: doctalk-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 15
